apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local:8080
    nginx.ingress.kubernetes.io/configuratio-snippet: |
      proxy_set_header 15d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header 15d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
    - host: auth.local.net
      http:
        paths:
          - path: /
            backend:
                serviceName: keycloak
                servicePort: 8080
    - http:
        paths:
          - path: /auth
            backend:
                serviceName: keycloak
                servicePort: 8080