apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  commonName: auth
  dnsNames:
    - auth.local.net
  ipAddresses:
    - 192.168.0.111
    - 127.0.0.1
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
    - host: auth.local.net
      http:
        paths:
          - path: /
            backend:
                serviceName: keycloak
                servicePort: 8080
    - http:
        paths:
          - path: /auth
            backend:
                serviceName: keycloak
                servicePort: 8080
  tls:
    - hosts:
      - auth.local.net
      secretName: keycloak-tls