apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: keycloak
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:12
        envFrom:
          - configMapRef:
              name: db-config
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: keycloak
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: keycloak
data:
  DB_VENDOR: postgres
  DB_ADDR: database
  DB_USER: keycloak
  DB_DATABASE: keycloak
  DB_PASSWORD: keycloak
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: password
  KEYCLOAK_PROXY_FORWARDING: 'true'
  KEYCLOAK_FRONTEND_URL: 'http://auth.local.net/auth'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:9.0.0
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080

